#! /usr/bin/env bash

set -euo pipefail

TEMP_DIR="/tmp/container-images-alpine"
YQ="$TEMP_DIR/yq"

if [ -d "$TEMP_DIR" ]; then
    rm -Rf "$TEMP_DIR"
fi
mkdir -p "$TEMP_DIR"

wget \
    --quiet \
    https://github.com/mikefarah/yq/releases/download/v4.33.2/yq_linux_amd64 \
    -O "$YQ"
chmod +x "$YQ"

echo $(curl --silent "https://dl-cdn.alpinelinux.org/alpine/latest-stable/releases/x86_64/latest-releases.yaml" | $YQ '.[0].version')